[package]
name = "rsocx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.13.0"
log = "0.4.14"
futures = "0.3.0"
async-std = {version = "1" , features = ["attributes"]}