[package]
name = "rsocx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.0"
simple_logger = "1.13.0"
log = "0.4.14"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.107"
errno = "0.2.8"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winsock2"] }